name: Open new issue
on:
  workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Open new issue
        env:
          GH_TOKEN: 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
        run: |
          gh issue create --repo QuentinBessot/grafana \
          --title "Issue title" --body "Issue body"
