name: Open new issue
on:
  workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Open new issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh issue create --repo QuentinBessot/grafana \
          --title "Issue title" --body "Issue body"
