name: Open new issue
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo QuentinBessot/grafana \
          create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: 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
